### ISSUE TITLE
Data from file

### ISSUE THREAD

**Issue by jeremycherfas** [sal0max/grav-plugin-shortcode-chart-js-plusplus#1]
Any chance you will be adding the ability to add chart data from a file?

**Comment by sal0max** [comment]
It's not planned. The Chart.js library doesn't support it out of the box, so this wrapper for Chart.js doesn't do it neither.

There are of course ways to visualize data from a file with Chart.js. But all of those solutions rely on a hand-written mapping function to feed the data to Chart.js. If I wanted to provide such a mapping to this Grav plugin, I'd have to dictate how the file has to be formatted. Would I choose csv? json? xml? What fields would I require?
In my opinion, this would drastically limit the use of this feature.

What are your opinions on that? What file type did you have in mind?

**Comment by jeremycherfas** [comment]
I quite understand. It was just a thought. For preference, I would go for JSON, but if you don't think it is worthwhile, then that's fine for me.
